### ISSUE TITLE
options

### ISSUE THREAD

**Issue by abouthiroppy** [abouthiroppy/sweetpack#3]
```yaml
dev:
  port: 8080
  contentBase: ''
  publicPath: ''
  dashboard: false
prod:
  extract: false
```
